# Convolutional Autoencoders with RAISIN


From "Introduction to Deep Learning - Deep Learning basics with Python, TensorFlow and Keras."
https://pythonprogramming.net/introduction-deep-learning-python-tensorflow-keras/

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

#--------------------------------------------------------60
code_created_by = 'Arturo_Avelino'
# On date: 2019.03.30 (yyyy.mm.dd)
code_name = 'VAE_RAISIN.ipynb'
version_code = '0.0.2'
last_update = '2019.04.01'
#--------------------------------------------------------60

In [2]:
import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'

# Based on: 
# https://stackoverflow.com/questions/53014306/error-15-initializing-libiomp5-dylib-but-found-libiomp5-dylib-already-initial
# This is to solve the problem that while running some ML notebooks the kernel shutdown
# with no apparent reason and the terminal prints the message:

# OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already
# initialized.
# OMP: Hint: This means that multiple copies of the OpenMP runtime have been
# linked into the program. That is dangerous, since it can degrade performance
# or cause incorrect results. The best thing to do is to ensure that only a
# single OpenMP runtime is linked into the process, e.g. by avoiding static
# linking of the OpenMP runtime in any library. As an unsafe, unsupported,
# undocumented workaround you can set the environment variable
# KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but
# that may cause crashes or silently produce incorrect results. For more
# information, please see http://www.intel.com/software/products/support/.

In [3]:
print(tf.__version__)
# 1.12.0

1.12.0


In [4]:
##############################################################################80

### Upload the data

In [5]:
# mnist = tf.keras.datasets.mnist

In [6]:
dirdata = '/Users/arturo/Dropbox/Research/Statistics/ML/Projects/RAISIN_ML/data/'
dirsaveoutput = dirdata

In [7]:
# y_train = np.array([-18.304, -18.280, -18.370, -18.409, -18.146])

y_train = np.array([1.,2.,3.,4.,5.])

In [8]:
y_train

array([1., 2., 3., 4., 5.])

In [9]:
y_train[0]

1.0

In [10]:
x_train = np.genfromtxt(dirdata+'data1.txt')

In [11]:
len(x_train)

5

In [12]:
len(x_train[0])

191

In [13]:
x_train[0]

array([  0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,   0.   ,
         0.   ,   0.   ,   0.   ,   0.   ,   0.   , -18.188, -18.235,
       -18.273, -18.3  , -18.319, -18.328, -18.33 , -18.325, -18.314,
       -18.298, -18.28 , -18.258, -18.236, -18.212, -18.187, -18.162,
       -18.136, -18.109, -18.08 , -18.049, -18.015, -17.976, -17.933,
       -17.885, -17.831, -17.771, -17.706, -17.635, -17.56 , -17.481,
       -17.399, -17.316, -17.233, -17.152, -17.074, -17.   , -16.93 ,
       -16.867, -16.81 , -16.761, -16.718, -16.682, -16.652, -16.628,
       -16.609, -16.

In [ ]:
# plt.imshow(x_train)
# plt.show

In [ ]:
# x_train = tf.keras.utils.normalize(x_train, axis=1)

In [ ]:
# x_train

-----

In [ ]:
# (x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
# len(x_train)

In [ ]:
# Each element of x_train[i] is a numpy array with 28 rows and each row
#  with 28 elements. The value of each entry is between [0, 255].
# So in total each submatrix has 28 x 28 = 784 entries

# x_train[0]

In [ ]:
# The label.
# y_train[0]
# 5

In [ ]:
#plt.imshow(x_train[0], cmap=plt.cm.binary)
#plt.show()

In [ ]:
#x_train = tf.keras.utils.normalize(x_train, axis=1)

In [ ]:
#x_test = tf.keras.utils.normalize(x_test, axis=1)

In [ ]:
# x_train[0]

### Build the model

In [54]:
y_train = np.array([-18.304, -18.280, -18.370, -18.409, -18.146])

# y_train = np.array([1.,2.,3.,4.,5.])

In [55]:
model = tf.keras.models.Sequential()

In [56]:
model.add(tf.keras.layers.Flatten())

In [57]:
model.add(tf.keras.layers.Dense(5, activation=tf.nn.relu))

In [58]:
# model.add(tf.keras.layers.Dense(5, activation=tf.nn.relu))

In [59]:
model.add(tf.keras.layers.Dense(1, activation=tf.nn.softmax))
# model.add(tf.keras.layers.Dense(1, activation='linear'))

In [60]:
# model.compile(optimizer='adam',
#               loss='sparse_categorical_crossentropy',
#               metrics=['accuracy'])

model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])

In [61]:
model.fit(x_train, y_train, epochs=3)

# Epoch 1/3
# 5/5 [==============================] - 1s 263ms/step - loss: 19.7885 - mean_absolute_error: 19.7885
# Epoch 2/3
# 5/5 [==============================] - 0s 375us/step - loss: 18.9759 - mean_absolute_error: 18.9759
# Epoch 3/3
# 5/5 [==============================] - 0s 558us/step - loss: 18.0706 - mean_absolute_error: 18.0706
# Out[41]:
# <tensorflow.python.keras.callbacks.History at 0xb3d2a44a8>

Epoch 1/3
5/5 [==============================] - 1s 101ms/step - loss: 19.3018 - mean_absolute_error: 19.3018
Epoch 2/3
5/5 [==============================] - 0s 344us/step - loss: 19.3018 - mean_absolute_error: 19.3018
Epoch 3/3
5/5 [==============================] - 0s 442us/step - loss: 19.3018 - mean_absolute_error: 19.3018


In [62]:
model.summary()

# _________________________________________________________________
# Layer (type)                 Output Shape              Param #   
# =================================================================
# flatten_2 (Flatten)          multiple                  0         
# _________________________________________________________________
# dense_5 (Dense)              multiple                  960       
# _________________________________________________________________
# dense_6 (Dense)              multiple                  6         
# =================================================================
# Total params: 966
# Trainable params: 966
# Non-trainable params: 0
# _________________________________________________________________

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          multiple                  0         
_________________________________________________________________
dense_7 (Dense)              multiple                  960       
_________________________________________________________________
dense_8 (Dense)              multiple                  6         
Total params: 966
Trainable params: 966
Non-trainable params: 0
_________________________________________________________________


In [43]:
# val_loss, val_acc = model.evaluate(x_test, y_test)
val_loss, val_acc = model.evaluate(x_train, y_train)

5/5 [==============================] - 0s 25ms/step


In [44]:
val_loss
# 17.363271713256836

17.363271713256836

In [45]:
val_acc
# 17.363271713256836

17.363271713256836

In [ ]:
type(x_train), type(y_train)

### Predict

In [46]:
predict = model.predict(x_train)

In [47]:
predict[0:5]

array([[-0.49957734],
       [ 1.5671172 ],
       [-2.61932   ],
       [-1.4020401 ],
       [-1.7388233 ]], dtype=float32)

In [48]:
predict[0]

array([-0.49957734], dtype=float32)

In [49]:
len(predict[0])

1

In [50]:
np.argmax(predict[0])

0

In [53]:
# plt.imshow(x_train[0], cmap = plt.cm.binary)
# plt.show()